# Generated by Django 4.2.7 on 2026-05-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0018_update_user_prompt'),
        ('decks', '0019_update_user_prompt'),
    ]

    operations = [
    ]
