# Generated by Django 4.2.7 on 2026-05-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0021_deck_call_notes_updated_at'),
        ('decks', '0021_founder_questions_sector'),
    ]

    operations = [
    ]
