# Generated by Django 4.2.7 on 2026-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0022_merge_20260507_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='industry_context',
            field=models.JSONField(default=dict),
        ),
    ]
